name: "uptodate - Keep your repository up to date."
description: "Keep your repo 'uptodate' by creating issues if a dependency updates."
branding:
  icon: bell
  color: green
inputs:
  config:
    description: "The location of the config file."
    required: true
    default: ".uptodate.yaml"
  token:
    description: "The token used for creating issues."
    required: false
    default: ${{ github.token }}
  repository:
    description: ""
    required: false
    default: ${{ github.repository }}
runs:
  using: "docker"
  image: "Dockerfile"
