name: uptodate
description: Keep your repo 'UpToDate'.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  version: ^2.0.0
  yaml: ^3.1.0
  yamltools: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.2
  mockito: ^5.0.16
  pedantic: ^1.9.0
  test: ^1.17.12
