name: CI

on:
  push:
  pull_request:

jobs:
  dart_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ${HOME}/.pub-cache
            .dart_tool
            .packages
          key: ${{ runner.os }}-${{ hashFiles('pubspec.lock') }}
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart test
